mvcWenbangiay/mvcWenbangiay/Controllers/ShoesStoreController.cs
using mvcWenbangiay.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using PagedList;
using PagedList.Mvc;

namespace mvcWenbangiay.Controllers
{
    public class ShoesStoreController : Controller
    {
        // GET: ShoesStore

        dbQLbangiayDataContext data = new dbQLbangiayDataContext();
        private List<GIAY> Laygiaymoi(int count)
        {
            return data.GIAYs.OrderByDescending(a => a.Ngaycapnhat).Take(count).ToList();
        }
        public ActionResult Index(int ? page, string Tukhoa, string currentFilter)
        {
            var lstProduct = new List<GIAY>();
            if (Tukhoa != null)
            {
                page = 1;
            }
            else
            {
                Tukhoa = currentFilter;
            }
            if (!string.IsNullOrEmpty(Tukhoa))
            {
                //lay ds theo tu khoa tim kiem
                lstProduct = data.GIAYs.Where(n => n.Tengiay.Contains(Tukhoa)).ToList();
            }
            else
            {
                //lay tat ca sp trong bang GIAY
                lstProduct = data.GIAYs.ToList();
            }
            ViewBag.CurrentFilter = Tukhoa;
            int pageNumber = (page ?? 1);
            int pageSize = 10;
            //sap xep sp theo id sp, sp moi dua len dau
            return View(lstProduct.ToPagedList(pageNumber, pageSize));



            ////tao  biến số sp trên mỗi trang
            //int pageSize = 10;
            ////tao bien so trang
            //int pageNum = (page ?? 1);

            ////Lay top 10 sp ban chay nhat

            //var giaymoi = Laygiaymoi(20);
            //return View(giaymoi.ToPagedList(pageNum,pageSize));
        }
        public ActionResult Loaigiay()
        {
            var loaigiay = from lg in data.LOAIGIAYs select lg;
            return PartialView(loaigiay);
        }
        public ActionResult Hanggiay()
        {
            var hanggiay = from hg in data.HANGGIAYs select hg;
            return PartialView(hanggiay);
        }
        public ActionResult SPTheoHanggiay(int id)
        {

            var giay = from g in data.GIAYs where g.MaHG == id select g;
            return View(giay);
        }
        public ActionResult SPTheoLoaigiay(int id)
        {
            var giay = from g in data.GIAYs where g.MaLG == id select g;
            return View(giay);
        }
        public ActionResult Details(int id)
        {
            var giay = from g in data.GIAYs
                       where g.Magiay == id
                       select g;
            return View(giay.Single());
        }
        public ActionResult Lienhe()
        {
            return View();
        }

    }
}

mvcWenbangiay/mvcWenbangiay/Views/ShoesStore/Details.cshtml
@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layoutchitiet.cshtml";
}

<div class="container single_product_container">
    <div class="row">
        <div class="col">

            <div class="breadcrumbs d-flex flex-row align-items-center">
                <ul>
                    <li><a href="index.html">Home</a></li>
                    <li><a href="categories.html"><i class="fa fa-angle-right" aria-hidden="true"></i>Men's</a></li>
                    <li class="active"><a href="#"><i class="fa fa-angle-right" aria-hidden="true"></i>Single Product</a></li>
                </ul>
            </div>

        </div>
    </div>

    <div class="row">
        <div class="col-lg-7">
            <div class="single_product_pics">
                <div class="row">
                    <div class="col-lg-3 thumbnails_col order-lg-1 order-2">
                        <div class="single_product_thumbnails">
                            <ul>
                                <li><img src="~/Hinhsanpham/@Model.Anhbia2" alt="" data-image="/Hinhsanpham/@Model.Anhbia2"></li>
                                <li class="active"><img src="~/Hinhsanpham/@Model.Anhbia" alt="" data-image="/Hinhsanpham/@Model.Anhbia"></li>
                                <li><img src="~/Hinhsanpham/@Model.Anhbia1" alt="" data-image="/Hinhsanpham/@Model.Anhbia1"></li>
                            </ul>
                        </div>
                    </div>
                    @*ảnh chính*@
                    <div class="col-lg-9 image_col order-lg-2 order-1">
                        <div class="single_product_image">
                            <div class="single_product_image_background" style="background-image:url(/Hinhsanpham/@Model.Anhbia)"></div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
        <div class="col-lg-5">
            <div class="product_details">
                <div class="product_details_title">
                    <h2>@Model.Tengiay</h2>
                    <p>@Html.Raw(Server.HtmlDecode(@Model.Mota))</p>

                </div>
                <div class="free_delivery d-flex flex-row align-items-center justify-content-center">
                    <span class="ti-truck"></span><span>free delivery</span>
                </div>
                @*giam gia*@
                @*<div class="original_price">$629.99</div>*@
                <div class="product_price">@String.Format("{0:0,0}", Model.Giaban) VNĐ</div>
                <ul class="star_rating">
                    <li><i class="fa fa-star" aria-hidden="true"></i></li>
                    <li><i class="fa fa-star" aria-hidden="true"></i></li>
                    <li><i class="fa fa-star" aria-hidden="true"></i></li>
                    <li><i class="fa fa-star" aria-hidden="true"></i></li>
                    <li><i class="fa fa-star-o" aria-hidden="true"></i></li>
                </ul>
                <div class="product_color">
                    <span>Select Size:</span>
                    <input type="radio" name="@Model.Size" /> @Model.Size
                    <!--<ul>-->
                    @*<li style="background: #e54e5d"></li>
                        <li style="background: #252525"></li>
                        <li style="background: #60b3f3"></li>*@
                    <!--<li><input type="radio" name="@Model.Size"/> @Model.Size</li>
                    </ul>-->
                </div>
                <div class="quantity d-flex flex-column flex-sm-row align-items-sm-center">
                    @*<span>Quantity:</span>
        <div class="quantity_selector">
            <span class="minus"><i class="fa fa-minus" aria-hidden="true"></i></span>
            <span id="quantity_value">1</span>
            <span class="plus"><i class="fa fa-plus" aria-hidden="true"></i></span>
        </div>*@
                    <div class="red_button add_to_cart_button"><a href="@Url.Action("ThemGiohang","GioHang",new { @iMagiay =@Model.Magiay,@strURL=Request.Url.ToString()})">Mua ngay</a></div>
                    @*<div class="red_button add_to_cart_button"><a href="@Url.Action("Payment","GioHang",new { @iGiaban =@Model.Giaban,@strURL=Request.Url.ToString()})">Thanh toán trực tuyến</a></div>*@
                    <div class="product_favorite d-flex flex-column align-items-center justify-content-center"></div>
                </div>
            </div>
        </div>
    </div>

</div>

<!-- Tabs -->

<!--<div class="tabs_section_container">

    <div class="container">
        <div class="row">
            <div class="col">
                <div class="tabs_container">
                    <ul class="tabs d-flex flex-sm-row flex-column align-items-left align-items-md-center justify-content-center">
                        <li class="tab active" data-active-tab="tab_1"><span>Description</span></li>
                        <li class="tab" data-active-tab="tab_2"><span>Additional Information</span></li>
                        <li class="tab" data-active-tab="tab_3"><span>Reviews (2)</span></li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col">-->

                <!-- Tab Description -->

                <!--<div id="tab_1" class="tab_container active">
                    <div class="row">
                        <div class="col-lg-5 desc_col">
                            <div class="tab_title">
                                <h4>Description</h4>
                            </div>
                            <div class="tab_text_block">
                                <h2>Pocket cotton sweatshirt</h2>
                                <p>Nam tempus turpis at metus scelerisque placerat nulla deumantos solicitud felis. Pellentesque diam dolor, elementum etos lobortis des mollis ut...</p>
                            </div>
                            <div class="tab_image">
                                <img src="~/images/desc_1.jpg" alt="">
                            </div>
                            <div class="tab_text_block">
                                <h2>Pocket cotton sweatshirt</h2>
                                <p>Nam tempus turpis at metus scelerisque placerat nulla deumantos solicitud felis. Pellentesque diam dolor, elementum etos lobortis des mollis ut...</p>
                            </div>
                        </div>
                        <div class="col-lg-5 offset-lg-2 desc_col">
                            <div class="tab_image">
                                <img src="~/images/desc_2.jpg" alt="">
                            </div>
                            <div class="tab_text_block">
                                <h2>Pocket cotton sweatshirt</h2>
                                <p>Nam tempus turpis at metus scelerisque placerat nulla deumantos solicitud felis. Pellentesque diam dolor, elementum etos lobortis des mollis ut...</p>
                            </div>
                            <div class="tab_image desc_last">
                                <img src="images/desc_3.jpg" alt="">
                            </div>
                        </div>
                    </div>
                </div>-->

                <!-- Tab Additional Info -->

                <!--<div id="tab_2" class="tab_container">
                    <div class="row">
                        <div class="col additional_info_col">
                            <div class="tab_title additional_info_title">
                                <h4>Additional Information</h4>
                            </div>
                            <p>COLOR:<span>Gold, Red</span></p>
                            <p>SIZE:<span>L,M,XL</span></p>
                        </div>
                    </div>
                </div>-->

                <!-- Tab Reviews -->

                <!--<div id="tab_3" class="tab_container">
                    <div class="row">-->

                        <!-- User Reviews -->

                        <!--<div class="col-lg-6 reviews_col">
                            <div class="tab_title reviews_title">
                                <h4>Reviews (2)</h4>
                            </div>-->

                            <!-- User Review -->

                            <!--<div class="user_review_container d-flex flex-column flex-sm-row">
                                <div class="user">
                                    <div class="user_pic"></div>
                                    <div class="user_rating">
                                        <ul class="star_rating">
                                            <li><i class="fa fa-star" aria-hidden="true"></i></li>
                                            <li><i class="fa fa-star" aria-hidden="true"></i></li>
                                            <li><i class="fa fa-star" aria-hidden="true"></i></li>
                                            <li><i class="fa fa-star" aria-hidden="true"></i></li>
                                            <li><i class="fa fa-star-o" aria-hidden="true"></i></li>
                                        </ul>
                                    </div>
                                </div>
                                <div class="review">
                                    <div class="review_date">27 Aug 2016</div>
                                    <div class="user_name">Brandon William</div>
                                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
                                </div>
                            </div>-->

                            <!-- User Review -->

                            <!--<div class="user_review_container d-flex flex-column flex-sm-row">
                                <div class="user">
                                    <div class="user_pic"></div>
                                    <div class="user_rating">
                                        <ul class="star_rating">
                                            <li><i class="fa fa-star" aria-hidden="true"></i></li>
                                            <li><i class="fa fa-star" aria-hidden="true"></i></li>
                                            <li><i class="fa fa-star" aria-hidden="true"></i></li>
                                            <li><i class="fa fa-star" aria-hidden="true"></i></li>
                                            <li><i class="fa fa-star-o" aria-hidden="true"></i></li>
                                        </ul>
                                    </div>
                                </div>
                                <div class="review">
                                    <div class="review_date">27 Aug 2016</div>
                                    <div class="user_name">Brandon William</div>
                                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
                                </div>
                            </div>
                        </div>-->

                        <!-- Add Review -->

                        <!--<div class="col-lg-6 add_review_col">

                            <div class="add_review">
                                <form id="review_form" action="post">
                                    <div>
                                        <h1>Add Review</h1>
                                        <input id="review_name" class="form_input input_name" type="text" name="name" placeholder="Name*" required="required" data-error="Name is required.">
                                        <input id="review_email" class="form_input input_email" type="email" name="email" placeholder="Email*" required="required" data-error="Valid email is required.">
                                    </div>
                                    <div>
                                        <h1>Your Rating:</h1>
                                        <ul class="user_star_rating">
                                            <li><i class="fa fa-star" aria-hidden="true"></i></li>
                                            <li><i class="fa fa-star" aria-hidden="true"></i></li>
                                            <li><i class="fa fa-star" aria-hidden="true"></i></li>
                                            <li><i class="fa fa-star" aria-hidden="true"></i></li>
                                            <li><i class="fa fa-star-o" aria-hidden="true"></i></li>
                                        </ul>
                                        <textarea id="review_message" class="input_review" name="message" placeholder="Your Review" rows="4" required data-error="Please, leave us a review."></textarea>
                                    </div>
                                    <div class="text-left text-sm-right">
                                        <button id="review_submit" type="submit" class="red_button review_submit_btn trans_300" value="Submit">submit</button>
                                    </div>
                                </form>
                            </div>

                        </div>

                    </div>
                </div>

            </div>
        </div>
    </div>

</div>-->

mvcWenbangiay/mvcWenbangiay/Views/ShoesStore/Hanggiay.cshtml
@model IEnumerable<mvcWenbangiay.Models.HANGGIAY>
@foreach (var item in Model)
{
    <a href="@Url.Action("SPTheoHanggiay","ShoesStore",new { id =item.MaHG})">
        @item.TenHG
    </a>
}

mvcWenbangiay/mvcWenbangiay/Views/ShoesStore/Index.cshtml
@using mvcWenbangiay.Models;
@using PagedList.Mvc;
@model PagedList.PagedList<GIAY>
@{
    ViewBag.Title = "Home";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}
<div class="row">
    <div class="col">
        <div class="product-grid" data-isotope='{ "itemSelector": ".product-item", "layoutMode": "fitRows" }'>
            @foreach (var giay in Model)
            {
                <div class="product-item men">
                    <div class="product discount product_filter">
                        <div class="product_image">
                            <a href="@Url.Action("Details", "ShoesStore", new { id = giay.Magiay })"><img alt="@giay.Tengiay" src="~/Hinhsanpham/@giay.Anhbia" /></a>
                            
                        </div>
                        <div class="favorite favorite_left"></div>
                        <div class="product_bubble product_bubble_right product_bubble_red d-flex flex-column align-items-center"><span>new</span></div>
                        <div class="product_info">
                            <h6 class="product_name"><a href="@Url.Action("Details", "ShoesStore", new { id = giay.Magiay })">@giay.Tengiay</a></h6>
                            <div class="product_price">@String.Format("{0:0,0}", giay.Giaban) VNĐ</div>
                        </div>
                    </div>
                    <div class="red_button add_to_cart_button"><a href="@Url.Action("ThemGiohang","GioHang",new { @iMagiay =giay.Magiay,@strURL=Request.Url.ToString()})">add to cart</a></div>
                </div>
            }
        </div>

    </div>
</div>
<hr />
@*tao lien ket cac trang*@
@*Trang @(Model.PageCount<Model.PageNumber?0:Model.PageNumber)/@Model.PageCount*@
<div class="MenuTrang">
    @Html.PagedListPager(Model, page => Url.Action("Index", new { page = page }))
</div>
<hr />
<style>

    .MenuTrang li {
        text-align: center;
        display: inline;
        width: 40px;
        height: 40px;
        border: 1px solid white;
        
    }
        .MenuTrang li:hover {
            background-color: cornflowerblue;
        }

    .MenuTrang a {
        text-align: center;
    }
</style>

mvcWenbangiay/mvcWenbangiay/Views/ShoesStore/Loaigiay.cshtml
@model IEnumerable<mvcWenbangiay.Models.LOAIGIAY>
@foreach(var item in Model)
{
    <a href="@Url.Action("SPTheoLoaigiay","ShoesStore",new { id =item.MaLG})">
        @item.TenLoaiGiay
    </a>
}

mvcWenbangiay/mvcWenbangiay/Views/ShoesStore/SPTheoHanggiay.cshtml
@model IEnumerable<mvcWenbangiay.Models.GIAY>
@{
    ViewBag.Title = "Home";
    Layout = "~/Views/Shared/_LayoutDanhmucsp.cshtml";
}

@*<h2>ĐÂY LÀ TRANG CHỦ</h2>*@


<div class="row">
    <div class="col">
        <div class="product-grid" data-isotope='{ "itemSelector": ".product-item", "layoutMode": "fitRows" }'>
            @foreach (var giay in Model)
            {
                <div class="product-item men">
                    <div class="product discount product_filter">
                        <div class="product_image">
                            <a href="@Url.Action("Details", "ShoesStore", new { id = giay.Magiay })"> <img alt="@giay.Tengiay" src="~/Hinhsanpham/@giay.Anhbia" /> </a>
                        </div>
                        <div class="favorite favorite_left"></div>
                        <div class="product_bubble product_bubble_right product_bubble_red d-flex flex-column align-items-center"><span>new</span></div>
                        <div class="product_info">
                            <h6 class="product_name"><a href="@Url.Action("Details", "ShoesStore", new { id = giay.Magiay })">@giay.Tengiay</a></h6>
                            <div class="product_price"> @String.Format("{0:0,0}", giay.Giaban) VNĐ</div>
                        </div>
                    </div>
                    <div class="red_button add_to_cart_button"><a href="@Url.Action("ThemGiohang","GioHang",new { @iMagiay =giay.Magiay,@strURL=Request.Url.ToString()})">add to cart</a></div>
                </div>
            }
        </div>

    </div>
</div>

mvcWenbangiay/mvcWenbangiay/Views/ShoesStore/SPTheoLoaigiay.cshtml
@model IEnumerable<mvcWenbangiay.Models.GIAY>
@{
    ViewBag.Title = "Home";
    Layout = "~/Views/Shared/_LayoutDanhmucsp.cshtml";
}

@*<h2>ĐÂY LÀ TRANG CHỦ</h2>*@
<div class="row">
    <div class="col">
        <div class="product-grid" data-isotope='{ "itemSelector": ".product-item", "layoutMode": "fitRows" }'>
            @foreach (var giay in Model)
            {
                <div class="product-item men">
                    <div class="product discount product_filter">
                        <div class="product_image">
                            <a href="@Url.Action("Details", "ShoesStore", new { id = giay.Magiay })"> <img alt="@giay.Tengiay" src="~/Hinhsanpham/@giay.Anhbia" /> </a>
                        </div>
                        <div class="favorite favorite_left"></div>
                        <div class="product_bubble product_bubble_right product_bubble_red d-flex flex-column align-items-center"><span>new</span></div>
                        <div class="product_info">
                            <h6 class="product_name"><a href="@Url.Action("Details", "ShoesStore", new { id = giay.Magiay })">@giay.Tengiay</a></h6>
                            <div class="product_price">@String.Format("{0:0,0}", giay.Giaban) VNĐ</div>
                        </div>
                    </div>
                    <div class="red_button add_to_cart_button"><a href="#">add to cart</a></div>
                </div>
            }
        </div>

    </div>
</div>